# Generated by Django 4.2.7 on 2023-12-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='uuid-hex'),
        ),
    ]
