# Generated by Django 4.2.7 on 2023-12-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_version_is_active'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='version',
            constraint=models.UniqueConstraint(fields=('num', 'product'), name='num_product_unique'),
        ),
    ]
