# Generated by Django 4.2.7 on 2023-12-23 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_description_alter_product_name'),
        ('product', '0003_version_num_product_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='version',
            name='num_product_unique',
        ),
        migrations.AlterUniqueTogether(
            name='version',
            unique_together={('num', 'product')},
        ),
    ]
