# Generated by Django 4.2.7 on 2023-12-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_version_num_product_unique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='активная?'),
        ),
    ]
