# Generated by Django 4.2.7 on 2023-12-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_version_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='version',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='version',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('product',), name='only_one_active_version_for_product'),
        ),
        migrations.AddConstraint(
            model_name='version',
            constraint=models.UniqueConstraint(fields=('num', 'product'), name='unique_together_version_num_and_product'),
        ),
    ]
