# Generated by Django 4.2.7 on 2023-11-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('slug', models.CharField(max_length=50, verbose_name='URL по понятиям')),
                ('message', models.TextField(verbose_name='содержимое')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='превью')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('visibility', models.BooleanField(default=True, verbose_name='признак публикации')),
                ('viewed', models.IntegerField(default=0, verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'Блог',
                'ordering': ('-date',),
            },
        ),
    ]
