# Generated by Django 4.2.7 on 2024-01-12 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'permissions': [('Moderator', 'Can edit description, category, is_published')], 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
    ]
